# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Umaint
tagline:          'Web developer from somewhere'
description:      'Hyde theme made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://umaint.github.io
baseurl:          /

author:
  name:           'Umaint'
  url:            https://umaint.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/umaint/umaint.github.io
