# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Umaint
tagline:          'Based on the Hyde theme'
description:      'Web developer from somewhere'
url:              https://umaint.github.io
baseurl:          https://umaint.github.io/

author:
  name:           'Umaint'
  url:            https://umaint.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/umaint/umaint.github.io
